#LATEST ANALYSIS

* The "IntelligentRounding" method MUST be improved as it fails in a number of scenarios such as the Bell Scenario and the Instrumental Biconfounding Scenario.

* Since the Bell Scenario failed due to the erroneous rounding of "y", mixed cardinality could not be tested properly. However, the absence of any error before the rounding makes a successful mixed cardinality check probable. Once the rounding is fixed more tests will be conducted on mixed cardinality.

The rest of the tests have been conducted successfully.

In [1]:
from __future__ import absolute_import
import numpy as np
from scipy.sparse import csr_matrix, coo_matrix
from itertools import combinations, chain, permutations
from igraph import Graph
from itertools import product
import json
from collections import defaultdict
from inflation.classestest import InflationLP,InflatedGraph

def ListOfBitStringsToListOfIntegers(list_of_bitstrings):
    return list(map(lambda s: int(s,4),list_of_bitstrings))
def UniformDistributionFromSupport(list_of_bitstrings):
    numvar = max(map(len,list_of_bitstrings))
    numevents = len(list_of_bitstrings)
    data = np.zeros(4 ** numvar)
    data[ListOfBitStringsToListOfIntegers(list_of_bitstrings)] = 1/numevents
    return data

def MixedCardinalityBaseConversion(cardinality, string):
    card=np.array([cardinality[i]**(len(cardinality)-(i+1)) for i in range(len(cardinality))])
    str_to_array=np.array([int(i) for i in string])
    return np.dot(card,str_to_array)
"""
import sys
sys.path.insert(0,'/Users/boraulu/opt/anaconda3/lib/python37.zip')
sys.path.insert(0,'/Users/boraulu/opt/anaconda3/lib/python3.7')
sys.path.insert(0,'/Users/boraulu/opt/anaconda3/lib/python3.7/lib-dynload')
sys.path.insert(0,'/Users/boraulu/opt/anaconda3/lib/python3.7/site-packages')
sys.path.insert(0,'/Users/boraulu/opt/anaconda3/lib/python3.7/lib-dynload')
sys.path.insert(0,'/Users/boraulu/opt/anaconda3/lib/python3.7/site-packages')
sys.path.insert(0,'/Users/boraulu/opt/anaconda3/lib/python3.7/site-packages/IPython/extensions')
sys.path.remove('/Users/boraulu/opt/anaconda3/envs/myenv/lib/python38.zip')
sys.path.remove('/Users/boraulu/opt/anaconda3/envs/myenv/lib/python3.8')
sys.path.remove('/Users/boraulu/opt/anaconda3/envs/myenv/lib/python3.8/lib-dynload')
sys.path.remove('/Users/boraulu/opt/anaconda3/envs/myenv/lib/python3.8/site-packages')
sys.path.remove('/Users/boraulu/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/IPython/extensions')

import sys
print(sys.path)
print(np.__version__)
""";

In [2]:
InstrumentalGraph = Graph.Formula("U1->X->A->B,U2->A:B")
BiconfoundingGraph = Graph.Formula("U1->A:B,U2->A:C,A->B:C")
Evans14a = Graph.Formula("U1->A:C,U2->A:B:D,U3->B:C:D,A->B,C->D")
Evans14b = Graph.Formula("U1->A:C,U2->B:C:D,U3->A:D,A->B,B:C->D")
Evans14c = Graph.Formula("U1->A:C,U2->B:D,U3->A:D,A->B->C->D")
IceCreamGraph = Graph.Formula("U1->A,U2->B:D,U3->C:D,A->B:C,B->D")
BiconfoundingInstrumental = Graph.Formula("U1->A,U2->B:C,U3->B:D,A->B,B->C:D")
TriangleGraph = Graph.Formula("X->A,Y->A:B,Z->B:C,X->C")
BellGraph = Graph.Formula("L->A:B,Ux->X,Uy->Y,X->A,Y->B")

TriangleData=[0.12199995751046305, 0.0022969343799089472, 0.001748319476328954, 3.999015242496535e-05, 0.028907881434196828, 0.0005736087488455967, 0.0003924033706699725, 1.1247230369521505e-05, 0.0030142577390317635, 0.09234476010282468, 4.373922921480586e-05, 0.0014533921021948346, 0.0007798079722868244, 0.024091567451515063, 1.1247230369521505e-05, 0.0003849052170902915, 0.020774884184769502, 0.000396152447459813, 0.0003049249122403608, 4.998769053120669e-06, 0.10820335492385, 0.0020794879260981982, 0.0015546171755205281, 2.4993845265603346e-05, 0.0006260958239033638, 0.020273757587194154, 7.498153579681003e-06, 0.0003374169110856452, 0.0028942872817568676, 0.08976414557915113, 2.624353752888351e-05, 0.0012984302615480939, 0.002370666223442477, 4.7488306004646356e-05, 0.0999928767540993, 0.001957018084296742, 0.0006198473625869629, 8.747845842961171e-06, 0.02636975644747481, 0.0005198719815245496, 1.4996307159362007e-05, 0.000403650601039494, 0.0005498645958432735, 0.017359475229224805, 7.123245900696953e-05, 0.002346922070440154, 0.0033754188031197316, 0.10295964618712641, 0.00038740460161685187, 7.498153579681003e-06, 0.01608353942841575, 0.000306174604503641, 0.0021319750011559654, 4.248953695152569e-05, 0.09107007399427891, 0.001860791780024169, 5.998522863744803e-05, 0.0018395470115484063, 0.002570616985567304, 0.0766411271224461, 1.874538394920251e-05, 0.00048238121362614454, 0.0006410921310627258, 0.020223769896662948]
InstrumentalData=['000','011']
InstrumentalData2=['000']
BiconfoundingData=['000','011']
BiconfoundingInstrumentalData=['0000','0100','1011','1111']
Evans14aData=['0000','1001','1111']
Evans14aData2=['0000','0010','0101']
Evans14bData=['1000','1001','1111']
Evans14cData=['0000','1101','1011']
IceCreamData=['0000','1111','1010','0011']
A=list(product('0123',repeat=4))
B=[''.join(i) for i in A]
del B[0]
BellDataIncomp=B

BellData=['0000','0010','0001','0020','0002','1011','0111','1100','1110','1101','1120','1102','0021','1121','0012','1112','0022','1122','0031','0131','0032','0132','0013','1013','0023','1023','0030','0130','0003','1003','0033','0133']
cardinality=[2,2,4,4]
original_card_product=np.prod(cardinality)
NonlBellData = np.zeros(original_card_product)
NonlBellData[list(map(lambda s: MixedCardinalityBaseConversion(cardinality, s),BellData))] = 1/len(BellData)
NonlBellData[MixedCardinalityBaseConversion(cardinality, '0033')]=1/16
NonlBellData[MixedCardinalityBaseConversion(cardinality, '0133')]=0
InflatedGraph(BellGraph,[4,1,4]).print_assessment()

For the graph who's parental structure is given by:
['L:X->A', 'L:Y->B', 'Ux->X', 'Uy->Y']
We utilize the following ordering of latent variables: [L,Ux,Uy]
We utilize the following ordering of observed variables: [A,B,X,Y]
We identify the following screening-off relationships relevant to enforcing determinism:
Sets given as (U1s,Ys,Xs) with the following meaning:	Ys are screened off from U1s by Xs.
([Uy],[B],[Y])
We identify the following screening-off non-ai expressible sets:
Sets given as (Y,Xs,Zs,U3s) with the following meaning:
Ys are screened off from Zs by Xs when U3s is different for (Y,Xs) vs Zs.
([A],[X],[B,Y],[L])
([B],[Y],[A,X],[L])
For inflation order [4, 1, 4]:
The inflated diagonal expressible set is given by:
[ 0  4 20 21]
And we count 2 other expressible sets, namely:
[ 0  8 20 21]
[ 1  4 20 21]
────────────────────────────────────────────────────────────────────────────────



In [3]:
rawgraph=InstrumentalGraph
rawdata=InstrumentalData

card=2
inflation_order=2
extra_ex=True
solver='moseklp'

InflatedGraph(rawgraph,inflation_order).print_assessment()
Output=InflationLP(rawgraph, rawdata, card, inflation_order,extra_ex,solver).Inequality()

For the graph who's parental structure is given by:
['U2:X->A', 'U2:A->B', 'U1->X']
We utilize the following ordering of latent variables: [U1,U2]
We utilize the following ordering of observed variables: [A,B,X]
We identify the following screening-off relationships relevant to enforcing determinism:
Sets given as (U1s,Ys,Xs) with the following meaning:	Ys are screened off from U1s by Xs.
([U1],[A],[X])
([U1],[B],[A])
We identify the following screening-off non-ai expressible sets:
Sets given as (Y,Xs,Zs,U3s) with the following meaning:
Ys are screened off from Zs by Xs when U3s is different for (Y,Xs) vs Zs.
([A],[X],[B],[U2])
([B],[X],[A],[U2])
For inflation order 2:
The inflated diagonal expressible set is given by:
[0 4 8 3 7 9]
And we count 2 other expressible sets, namely:
[0 5 8]
[1 4 8]
────────────────────────────────────────────────────────────────────────────────

Inferred primal variable count: 52
Inferred dual variable count: 294
LP constructed, initiated optimizer.
Open fi

In [6]:
rawgraph=InstrumentalGraph
rawdata=InstrumentalData

card=[2,2,2]
inflation_order=2
extra_ex=True
solver='moseklp'

InflatedGraph(rawgraph,inflation_order).print_assessment()
Output=InflationLP(rawgraph, rawdata, card, inflation_order,extra_ex,solver).Inequality()

For the graph who's parental structure is given by:
['U2:X->A', 'U2:A->B', 'U1->X']
We utilize the following ordering of latent variables: [U1,U2]
We utilize the following ordering of observed variables: [A,B,X]
We identify the following screening-off relationships relevant to enforcing determinism:
Sets given as (U1s,Ys,Xs) with the following meaning:	Ys are screened off from U1s by Xs.
([U1],[A],[X])
([U1],[B],[A])
We identify the following screening-off non-ai expressible sets:
Sets given as (Y,Xs,Zs,U3s) with the following meaning:
Ys are screened off from Zs by Xs when U3s is different for (Y,Xs) vs Zs.
([A],[X],[B],[U2])
([B],[X],[A],[U2])
For inflation order 2:
The inflated diagonal expressible set is given by:
[0 4 8 3 7 9]
And we count 2 other expressible sets, namely:
[0 5 8]
[1 4 8]
────────────────────────────────────────────────────────────────────────────────

Inferred primal variable count: 52
Inferred dual variable count: 294
LP constructed, initiated optimizer.
Open fi

In [4]:
rawgraph=InstrumentalGraph
rawdata=3

card=2
inflation_order=2
extra_ex=True
solver='moseklp'

InflatedGraph(rawgraph,inflation_order).print_assessment()
Output=InflationLP(rawgraph, rawdata, card, inflation_order,extra_ex,solver).Inequality()

For the graph who's parental structure is given by:
['U2:X->A', 'U2:A->B', 'U1->X']
We utilize the following ordering of latent variables: [U1,U2]
We utilize the following ordering of observed variables: [A,B,X]
We identify the following screening-off relationships relevant to enforcing determinism:
Sets given as (U1s,Ys,Xs) with the following meaning:	Ys are screened off from U1s by Xs.
([U1],[A],[X])
([U1],[B],[A])
We identify the following screening-off non-ai expressible sets:
Sets given as (Y,Xs,Zs,U3s) with the following meaning:
Ys are screened off from Zs by Xs when U3s is different for (Y,Xs) vs Zs.
([A],[X],[B],[U2])
([B],[X],[A],[U2])
For inflation order 2:
The inflated diagonal expressible set is given by:
[0 4 8 3 7 9]
And we count 2 other expressible sets, namely:
[0 5 8]
[1 4 8]
────────────────────────────────────────────────────────────────────────────────

Inferred primal variable count: 52
Inferred dual variable count: 294
LP constructed, initiated optimizer.
Open fi

In [5]:
rawgraph=TriangleGraph
rawdata=TriangleData

card=4
inflation_order=2
extra_ex=True
solver='moseklp'

InflatedGraph(rawgraph,inflation_order).print_assessment()
Output=InflationLP(rawgraph, rawdata, card, inflation_order,extra_ex,solver).Inequality()

For the graph who's parental structure is given by:
['X:Y->A', 'Y:Z->B', 'X:Z->C']
We utilize the following ordering of latent variables: [X,Y,Z]
We utilize the following ordering of observed variables: [A,B,C]
We identify the following screening-off relationships relevant to enforcing determinism:
Sets given as (U1s,Ys,Xs) with the following meaning:	Ys are screened off from U1s by Xs.
We identify the following screening-off non-ai expressible sets:
Sets given as (Y,Xs,Zs,U3s) with the following meaning:
Ys are screened off from Zs by Xs when U3s is different for (Y,Xs) vs Zs.
For inflation order 2:
The inflated diagonal expressible set is given by:
[ 0  4  8  3  7 11]
And we count 0 other expressible sets, namely:
────────────────────────────────────────────────────────────────────────────────

Inferred primal variable count: 2080
Inferred dual variable count: 2123776
LP constructed, initiated optimizer.
Open file 'mosek_prob.jtask'
Start writing.
done writing. Time: 1.86

Problem
  

ValueError: no symbols given

In [6]:
rawgraph=BiconfoundingGraph
rawdata=BiconfoundingData

card=2
inflation_order=2
extra_ex=True
solver='moseklp'

InflatedGraph(rawgraph,inflation_order).print_assessment()
Output=InflationLP(rawgraph, rawdata, card, inflation_order,extra_ex,solver).Inequality()

For the graph who's parental structure is given by:
['U1:U2->A', 'U1:A->B', 'U2:A->C']
We utilize the following ordering of latent variables: [U1,U2]
We utilize the following ordering of observed variables: [A,B,C]
We identify the following screening-off relationships relevant to enforcing determinism:
Sets given as (U1s,Ys,Xs) with the following meaning:	Ys are screened off from U1s by Xs.
([U2],[B],[A])
([U1],[C],[A])
We identify the following screening-off non-ai expressible sets:
Sets given as (Y,Xs,Zs,U3s) with the following meaning:
Ys are screened off from Zs by Xs when U3s is different for (Y,Xs) vs Zs.
For inflation order 2:
The inflated diagonal expressible set is given by:
[ 0  4  8  3  7 11]
And we count 0 other expressible sets, namely:
────────────────────────────────────────────────────────────────────────────────

Inferred primal variable count: 36
Inferred dual variable count: 362
LP constructed, initiated optimizer.
Open file 'mosek_prob.jtask'
Start writing.
done wri

In [7]:
rawgraph=Evans14a
rawdata=Evans14aData

card=2
inflation_order=2
extra_ex=True
solver='moseklp'

InflatedGraph(rawgraph,inflation_order).print_assessment()
Output=InflationLP(rawgraph, rawdata, card, inflation_order,extra_ex,solver).Inequality()

For the graph who's parental structure is given by:
['U1:U2->A', 'U2:U3:A->B', 'U1:U3->C', 'U2:U3:C->D']
We utilize the following ordering of latent variables: [U1,U2,U3]
We utilize the following ordering of observed variables: [A,B,C,D]
We identify the following screening-off relationships relevant to enforcing determinism:
Sets given as (U1s,Ys,Xs) with the following meaning:	Ys are screened off from U1s by Xs.
([U1],[B],[A])
([U1],[D],[C])
We identify the following screening-off non-ai expressible sets:
Sets given as (Y,Xs,Zs,U3s) with the following meaning:
Ys are screened off from Zs by Xs when U3s is different for (Y,Xs) vs Zs.
([B],[A],[C],[U3])
([D],[C],[A],[U2])
For inflation order 2:
The inflated diagonal expressible set is given by:
[ 0  4 12 16  3 11 15 23]
And we count 2 other expressible sets, namely:
[ 0  4 13]
[ 1 12 16]
────────────────────────────────────────────────────────────────────────────────

Inferred primal variable count: 152
Inferred dual variable count: 967

In [8]:
rawgraph=Evans14b
rawdata=Evans14bData

card=2
inflation_order=2
extra_ex=True
solver='moseklp'

InflatedGraph(rawgraph,inflation_order).print_assessment()
Output=InflationLP(rawgraph, rawdata, card, inflation_order,extra_ex,solver).Inequality()

For the graph who's parental structure is given by:
['U1:U3->A', 'U2:A->B', 'U1:U2->C', 'U2:U3:B:C->D']
We utilize the following ordering of latent variables: [U1,U2,U3]
We utilize the following ordering of observed variables: [A,B,C,D]
We identify the following screening-off relationships relevant to enforcing determinism:
Sets given as (U1s,Ys,Xs) with the following meaning:	Ys are screened off from U1s by Xs.
([U1],[B],[A])
([U3],[B],[A])
([U1,U3],[B],[A])
([U1],[D],[B,C])
We identify the following screening-off non-ai expressible sets:
Sets given as (Y,Xs,Zs,U3s) with the following meaning:
Ys are screened off from Zs by Xs when U3s is different for (Y,Xs) vs Zs.
([B],[A],[C],[U2])
([B],[A],[C,D],[U2])
For inflation order 2:
The inflated diagonal expressible set is given by:
[ 0  4 12 16  3 11 15 23]
And we count 2 other expressible sets, namely:
[ 0  4 13]
[ 0  4 13 18]
────────────────────────────────────────────────────────────────────────────────

Inferred primal variable count

In [9]:
rawgraph=Evans14c
rawdata=Evans14cData

card=2
inflation_order=2
extra_ex=True
solver='moseklp'

InflatedGraph(rawgraph,inflation_order).print_assessment()
Output=InflationLP(rawgraph, rawdata, card, inflation_order,extra_ex,solver).Inequality()

For the graph who's parental structure is given by:
['U1:U3->A', 'U2:A->B', 'U1:B->C', 'U2:U3:C->D']
We utilize the following ordering of latent variables: [U1,U2,U3]
We utilize the following ordering of observed variables: [A,B,C,D]
We identify the following screening-off relationships relevant to enforcing determinism:
Sets given as (U1s,Ys,Xs) with the following meaning:	Ys are screened off from U1s by Xs.
([U1],[B],[A])
([U3],[B],[A])
([U1,U3],[B],[A])
([U2],[C],[B])
([U3],[C],[B])
([U2,U3],[C],[B])
([U1],[D],[C])
We identify the following screening-off non-ai expressible sets:
Sets given as (Y,Xs,Zs,U3s) with the following meaning:
Ys are screened off from Zs by Xs when U3s is different for (Y,Xs) vs Zs.
([B],[A],[C,D],[U2])
For inflation order 2:
The inflated diagonal expressible set is given by:
[ 0  4 12 20  3 11 19 27]
And we count 1 other expressible sets, namely:
[ 0  4 14 22]
────────────────────────────────────────────────────────────────────────────────

Inferred primal v

In [10]:
rawgraph=IceCreamGraph
rawdata=IceCreamData

card=2
inflation_order=2
extra_ex=True
solver='moseklp'

InflatedGraph(rawgraph,inflation_order).print_assessment()
Output=InflationLP(rawgraph, rawdata, card, inflation_order,extra_ex,solver).Inequality()

For the graph who's parental structure is given by:
['U1->A', 'U2:A->B', 'U3:A->C', 'U2:U3:B->D']
We utilize the following ordering of latent variables: [U1,U2,U3]
We utilize the following ordering of observed variables: [A,B,C,D]
We identify the following screening-off relationships relevant to enforcing determinism:
Sets given as (U1s,Ys,Xs) with the following meaning:	Ys are screened off from U1s by Xs.
([U1],[B],[A])
([U1],[C],[A])
([U1],[D],[B])
We identify the following screening-off non-ai expressible sets:
Sets given as (Y,Xs,Zs,U3s) with the following meaning:
Ys are screened off from Zs by Xs when U3s is different for (Y,Xs) vs Zs.
([B],[A],[C,D],[U2])
([C],[A],[B,D],[U3])
([D],[A],[B,C],[U2,U3])
For inflation order 2:
The inflated diagonal expressible set is given by:
[ 0  2  6 10  1  5  9 17]
And we count 3 other expressible sets, namely:
[ 0  2  6 12]
[ 0  2  6 11]
[ 0  3  7 10]
────────────────────────────────────────────────────────────────────────────────

Inferred prim

In [3]:
rawgraph=BiconfoundingInstrumental
rawdata=BiconfoundingInstrumentalData

card=2
inflation_order=2
extra_ex=True
solver='moseklp'

InflatedGraph(rawgraph,inflation_order).print_assessment()
Output=InflationLP(rawgraph, rawdata, card, inflation_order,extra_ex,solver).Inequality()

For the graph who's parental structure is given by:
['U1->A', 'U2:U3:A->B', 'U2:B->C', 'U3:B->D']
We utilize the following ordering of latent variables: [U1,U2,U3]
We utilize the following ordering of observed variables: [A,B,C,D]
We identify the following screening-off relationships relevant to enforcing determinism:
Sets given as (U1s,Ys,Xs) with the following meaning:	Ys are screened off from U1s by Xs.
([U1],[B],[A])
([U1],[C],[B])
([U3],[C],[B])
([U1,U3],[C],[B])
([U1],[D],[B])
([U2],[D],[B])
([U1,U2],[D],[B])
We identify the following screening-off non-ai expressible sets:
Sets given as (Y,Xs,Zs,U3s) with the following meaning:
Ys are screened off from Zs by Xs when U3s is different for (Y,Xs) vs Zs.
([B],[A],[C,D],[U2,U3])
([C],[A],[B,D],[U2,U3])
([D],[A],[B,C],[U2,U3])
For inflation order 2:
The inflated diagonal expressible set is given by:
[ 0  2 10 18  1  9 17 25]
And we count 3 other expressible sets, namely:
[ 0  2 13 21]
[ 0  5 10 21]
[ 0  5 13 18]
───────────────────────

AssertionError: The rounding of y has failed: checkY.min()=-21600.0

In [4]:
rawgraph=BellGraph
rawdata=NonlBellData

card=[2,2,4,4]
inflation_order=2
extra_ex=True
solver='moseklp'

InflatedGraph(rawgraph,inflation_order).print_assessment()
Output=InflationLP(rawgraph, rawdata, card, inflation_order,extra_ex,solver).Inequality()

For the graph who's parental structure is given by:
['L:X->A', 'L:Y->B', 'Ux->X', 'Uy->Y']
We utilize the following ordering of latent variables: [L,Ux,Uy]
We utilize the following ordering of observed variables: [A,B,X,Y]
We identify the following screening-off relationships relevant to enforcing determinism:
Sets given as (U1s,Ys,Xs) with the following meaning:	Ys are screened off from U1s by Xs.
([Ux],[A],[X])
([Uy],[B],[Y])
We identify the following screening-off non-ai expressible sets:
Sets given as (Y,Xs,Zs,U3s) with the following meaning:
Ys are screened off from Zs by Xs when U3s is different for (Y,Xs) vs Zs.
([A],[X],[B,Y],[L])
([B],[Y],[A,X],[L])
For inflation order 2:
The inflated diagonal expressible set is given by:
[ 0  4  8 10  3  7  9 11]
And we count 2 other expressible sets, namely:
[ 0  6  8 10]
[ 2  4  8 10]
────────────────────────────────────────────────────────────────────────────────

Inferred primal variable count: 2208
Inferred dual variable count: 11574
LP 

AssertionError: The rounding of y has failed: checkY.min()=-2730672.0